spring.application.name=base_team
sever.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/base_team
spring.datasource.username = elianeytor
spring.datasource.password 
spring.datasource.datasource.driver-class-name = org.postgresql.Driver
    